In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn import metrics

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
from sklearn import svm

In [5]:
from sklearn.tree import DecisionTreeClassifier

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
iris = pd.read_csv("iris.csv")

In [8]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
iris.head

<bound method NDFrame.head of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [26]:
train,test = train_test_split(iris,test_size=0.25)

In [24]:
test

8          setosa
42         setosa
83     versicolor
52     versicolor
80     versicolor
133     virginica
135     virginica
76     versicolor
94     versicolor
77     versicolor
98     versicolor
48         setosa
9          setosa
3          setosa
86     versicolor
107     virginica
117     virginica
99     versicolor
58     versicolor
136     virginica
95     versicolor
146     virginica
128     virginica
119     virginica
24         setosa
141     virginica
14         setosa
46         setosa
59     versicolor
25         setosa
2          setosa
142     virginica
44         setosa
121     virginica
108     virginica
123     virginica
148     virginica
63     versicolor
Name: species, dtype: object

In [29]:
train_X=train[['sepal_length','sepal_width','petal_length','petal_width']]

In [28]:
train_y=train.species

In [27]:
train_X

sepal_length  sepal_width  petal_length  petal_width
13            4.3          3.0           1.1          0.1
130           7.4          2.8           6.1          1.9
41            4.5          2.3           1.3          0.3
126           6.2          2.8           4.8          1.8
97            6.2          2.9           4.3          1.3
..            ...          ...           ...          ...
137           6.4          3.1           5.5          1.8
68            6.2          2.2           4.5          1.5
78            6.0          2.9           4.5          1.5
7             5.0          3.4           1.5          0.2
140           6.7          3.1           5.6          2.4

[112 rows x 4 columns]

In [16]:
train_y

13         setosa
130     virginica
41         setosa
126     virginica
97     versicolor
          ...    
137     virginica
68     versicolor
78     versicolor
7          setosa
140     virginica
Name: species, Length: 112, dtype: object

In [32]:
test_X = test[['sepal_length','sepal_width','petal_length','petal_width']]
test_Y=test.species

In [33]:
model = svm.SVC()

In [34]:
model.fit(train_X,train_y)
pred = model.predict(test_X)

In [37]:
metrics.accuracy_score(pred,test_Y)

1.0

In [38]:
model = DecisionTreeClassifier()

In [39]:
model.fit(train_X,train_y)

DecisionTreeClassifier()

In [40]:
pred = model.predict(test_X)
metrics.accuracy_score(pred,test_Y)

0.9473684210526315

In [41]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

# Split the dataset into training and testing sets
train, test = train_test_split(iris, test_size=0.25)
train_X = train[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
train_y = train.species
test_X = test[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
test_Y = test.species

# Support Vector Machine (SVM) Classifier
svm_model = svm.SVC()
svm_model.fit(train_X, train_y)
svm_pred = svm_model.predict(test_X)
svm_accuracy = metrics.accuracy_score(svm_pred, test_Y)
print("SVM Accuracy:", svm_accuracy)

# Decision Tree Classifier
dt_model = DecisionTreeClassifier()
dt_model.fit(train_X, train_y)
dt_pred = dt_model.predict(test_X)
dt_accuracy = metrics.accuracy_score(dt_pred, test_Y)
print("Decision Tree Accuracy:", dt_accuracy)

# Random Forest Classifier
rf_model = RandomForestClassifier()
rf_model.fit(train_X, train_y)
rf_pred = rf_model.predict(test_X)
rf_accuracy = metrics.accuracy_score(rf_pred, test_Y)
print("Random Forest Accuracy:", rf_accuracy)

# K-Nearest Neighbors (KNN) Classifier
knn_model = KNeighborsClassifier()
knn_model.fit(train_X, train_y)
knn_pred = knn_model.predict(test_X)
knn_accuracy = metrics.accuracy_score(knn_pred, test_Y)
print("KNN Accuracy:", knn_accuracy)

# Naive Bayes Classifier
nb_model = GaussianNB()
nb_model.fit(train_X, train_y)
nb_pred = nb_model.predict(test_X)
nb_accuracy = metrics.accuracy_score(nb_pred, test_Y)
print("Naive Bayes Accuracy:", nb_accuracy)


SVM Accuracy: 1.0
Decision Tree Accuracy: 0.9473684210526315
Random Forest Accuracy: 0.9736842105263158
KNN Accuracy: 1.0
Naive Bayes Accuracy: 0.9736842105263158


In [42]:
from sklearn.metrics import confusion_matrix, classification_report

# For SVM model (replace with the model you are interested in)
svm_cm = confusion_matrix(test_Y, svm_pred)
svm_classification_report = classification_report(test_Y, svm_pred)
print("SVM Confusion Matrix:\n", svm_cm)
print("SVM Classification Report:\n", svm_classification_report)


SVM Confusion Matrix:
 [[20  0  0]
 [ 0 10  0]
 [ 0  0  8]]
SVM Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        20
  versicolor       1.00      1.00      1.00        10
   virginica       1.00      1.00      1.00         8

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

